export const BLOG_POST_CREATE_REQUEST = 'BLOG_POST_CREATE_REQUEST';
export const BLOG_POST_CREATE_SUCCESS = 'BLOG_POST_CREATE_SUCCESS';
export const BLOG_POST_CREATE_FAIL = 'BLOG_POST_CREATE_FAIL';
export const BLOG_POST_CREATE_RESET = 'BLOG_POST_CREATE_RESET';

export const BLOG_POST_DELETE_REQUEST = 'BLOG_POST_DELETE_REQUEST';
export const BLOG_POST_DELETE_SUCCESS = 'BLOG_POST_DELETE_SUCCESS';
export const BLOG_POST_DELETE_FAIL = 'BLOG_POST_DELETE_FAIL';

export const BLOG_POST_DETAILS_REQUEST = 'BLOG_POST_DETAILS_REQUEST';
export const BLOG_POST_DETAILS_SUCCESS = 'BLOG_POST_DETAILS_SUCCESS';
export const BLOG_POST_DETAILS_FAIL = 'BLOG_POST_DETAILS_FAIL';

export const BLOG_POST_LIKE_UNLIKE_REQUEST = 'BLOG_POST_LIKE_UNLIKE_REQUEST';
export const BLOG_POST_LIKE_UNLIKE_SUCCESS = 'BLOG_POST_LIKE_UNLIKE_SUCCESS';
export const BLOG_POST_LIKE_UNLIKE_FAIL = 'BLOG_POST_LIKE_UNLIKE_FAIL';
export const BLOG_POST_UPDATE_IN_LIST = 'BLOG_POST_UPDATE_IN_LIST';

export const BLOG_CREATE_COMMENT_REQUEST = 'BLOG_CREATE_COMMENT_REQUEST';
export const BLOG_CREATE_COMMENT_SUCCESS = 'BLOG_CREATE_COMMENT_SUCCESS';
export const BLOG_CREATE_COMMENT_FAIL = 'BLOG_CREATE_COMMENT_FAIL';

export const BLOG_GET_COMMENT_REQUEST = 'BLOG_GET_COMMENT_REQUEST';
export const BLOG_GET_COMMENT_SUCCESS = 'BLOG_GET_COMMENT_SUCCESS';
export const BLOG_GET_COMMENT_FAIL = 'BLOG_GET_COMMENT_FAIL';

export const BLOG_LIST_MY_REQUEST = 'BLOG_LIST_MY_REQUEST';
export const BLOG_LIST_MY_SUCCESS = 'BLOG_LIST_MY_SUCCESS';
export const BLOG_LIST_MY_FAIL = 'BLOG_LIST_MY_FAIL';

export const BLOG_LIST_REQUEST = 'BLOG_LIST_REQUEST';
export const BLOG_LIST_SUCCESS = 'BLOG_LIST_SUCCESS';
export const BLOG_LIST_FAIL = 'BLOG_LIST_FAIL';
