# Generated by Django 5.1 on 2024-10-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='static/images/placeholder.jpg', null=True, upload_to='static/images/'),
        ),
    ]
