# Generated by Django 5.1 on 2024-08-14 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_brand_product_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='type',
            new_name='_type',
        ),
    ]
