// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// Command: npx gltfjsx@6.5.0 earth.gltf
// Author: PatelDev (https://sketchfab.com/PatelDev)
// License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
// Source: https://sketchfab.com/3d-models/earth-f7a76c63ff1846afb2d606e5c8369c15
// Title: Earth
// */

import React from 'react';
import { useGLTF } from '@react-three/drei';

export default function Model(props) {
  const { nodes, materials } = useGLTF('/earth.gltf');
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials['Scene_-_Root']}
        scale={3}
      />
    </group>
  );
}

useGLTF.preload('/earth.gltf');
// import { useRef } from 'react';
// import { useFrame } from '@react-three/fiber';
// import { Sphere } from '@react-three/drei';

// function Earth() {
//   const earthRef = useRef();

//   useFrame(() => {
//     // Rotate the Earth model
//     earthRef.current.rotation.y += 0.01;
//   });

//   return (
//     <Sphere ref={earthRef} args={[1, 32, 32]}>
//       <meshStandardMaterial color="blue" />
//     </Sphere>
//   );
// }

// export default Earth;
